.TH aquarius 4 . . "stars wiki"
.SH AQUARIUS ♒
.B Ruled by:
Uranus
.br
.B Mode:
Fixed
.br
.B Element:
Air
.br
.B Polarity:
Positive
.br
.B House:
11
.br
.B Date range:
Jan 20 - Feb 18
.br
.B Symbol:
the Water Bearer
.br
 
.br
Aquarius is a fascinating, enigmatic, and unique sign. Aquarians tend to be very passionate about justice and truth, but also calculating and analytical. They tend to have unique points of view on things and are very idealistic. It often seems as though Aquarians are aloof and stuck in their own little worlds, so it can be difficult to interact with Aquarians if you don't "get" them.
.br
 
.br
Fun fact: Because of their unique points of view, Aquarians are incredible drivers for social change. Charles Darwin, Galileo Galilei, Abraham Lincoln, and Rosa Parks were all trailblazing Aquarians - if not for Aquarians, we might not know about natural selection and we might still think the Sun orbits the Earth!