.TH aries 4 . . "stars wiki"
.SH ARIES ♈
.B Ruled by:
Mars
.br
.B Mode:
Cardinal
.br
.B Element:
Fire
.br
.B Polarity:
Positive
.br
.B House:
1
.br
.B Date range:
Mar 21 - Apr 19
.br
.B Symbol:
the Ram
.br
 
.br
Aries is the first sign of the zodiac, and it shows! Aries placements tend to put themselves first and have a go-getter attitude. Aries are brave and well-suited to leadership, and can have a pretty bad temper too. 
.br

.br
Fun fact: Many tremendously popular celebrities have their sun in Aries, including Alec Baldwin, Lady Gaga, Kourtney Kardashian, and Emma Watson.