.TH ic 5 . . "stars wiki"
.SH IC
The IC, short for imum coeli, is the point in space where the ecliptic crosses the prime meridian opposite the midheaven (see also: mc).
The sign of the IC is related to parental and home relationships; which parent it represents is argued, traditionally the mother but some also believe it deals with the father.
The IC represents foundations and roots rather than progression or contributions; it relates to childhood and the innermost environment, which it affects in tandem with the Moon.  

.SH SEE ALSO
    mc
    dc
    ascendant
    ecliptic
    moon