.TH pisces 4 . . "stars wiki"
.SH PISCES ♓
.B Ruled by:
Jupiter, Neptune
.br
.B Mode:
Mutable
.br
.B Element:
Water
.br
.B Polarity:
Negative
.br
.B House:
12
.br
.B Date range:
Feb 19 - March 20
.br
.B Symbol:
the Two Fishes
.br
 
.br
Pisces is the final sign of the zodiac.
Those with sun in Pisces are typically introspective, empathetic, and quiet, and feel emotions more strongly than others.
Pisces placements also may be naive and susceptible to tricks and misinformation.
.br
 
.br
Fun fact: Jesus Christ is thought to have been a Pisces!