.TH водолей 4 . . "вики stars"
.SH ВОДОЛЕЙ ♒
.B Ruled by:
Uranus
.br
.B Mode:
Fixed
.br
.B Element:
Духа
.br
.B Polarity:
Positive
.br
.B Дом:
11-ый
.B Date range:
20-ое января - 18-ое февраля

Водолей — загадочный и уникальный знак. Водолей обычно очень страстный о справедливости и правде, а тоже расчетливый и аналитический. У него обычно есть уникальные и идеалические точки зрения. Часто кажется, что Водолей отчужденный и живет во своем мире, поэтому может быть сложно взаимодействовать с Водолеем, если его личность не понят.

Интересный факт: Из-за его уникальных точек зрения, Водолей часто водитель социальных перемен. Чарльз Дарвин, Галилео Галилеи, Авраам Линкольн, и Роза Паркс — все были новаторскими Водолеями. Если бы не было Водолея, мы, может, не бы знали о естественном отборе и мы еще бы думали, что Солнце возвращается вокруг Земли!