.TH водолей 4 . . "вики stars"
.SH ВОДОЛЕЙ ♒
.B Управляющая:
Уран
.br
.B Качество:
Фиксированное
.br
.B Стихия:
Воздух
.br
.B Полярность:
Позитивная
.br
.B Дом:
11-ый
.B Родились:
20 января - 18 февраля
.br

Водолей — загадочный и уникальный знак. Водолей обычно очень страстный о справедливости и правде, а тоже расчетливый и аналитический. У него обычно есть уникальные и идеалические точки зрения. Часто кажется, что Водолей отчужденный и живет во своем мире, поэтому может быть сложно взаимодействовать с Водолеем, если его личность не понят.

Интересный факт: Из-за его уникальных точек зрения, Водолей часто водитель социальных перемен. Чарльз Дарвин, Галилео Галилеи, Авраам Линкольн, и Роза Паркс — все были новаторскими Водолеями. Если бы не было Водолея, мы, может, не бы знали о естественном отборе и мы еще бы думали, что Солнце возвращается вокруг Земли!