.TH овен 4 . . "stars wiki"
.SH ОВЕН ♈
.B Управляющая:
Марс
.br
.B Качество:
Кардинальное
.br
.B Стихия:
Огонь
.br
.B Полярность:
Позитивная
.br
.B Дом:
1-ый
.br
.B Родились:
21 марта - 19 апреля
.br
 
.br
Овен — первый знак зодиака, и видно! Овен часто себя ставит на первое место и имеет предприимчивое отношение. Овен смелый и хорошо подходит для лидерства, и имеет злой нрав. 
.br

.br
Интересный факт: Многие чрезвычайно популярные звезды Овены, например Алек Балдвин, Лейди Гага, Коуртни Кардашян, и Эмма Уатсон.