.TH negative 2 . . "stars wiki"
.SH NEGATIVE SIGNS
The negative signs are the members of the earth and water trios: Capricorn, Taurus, Virgo; Cancer, Scorpio, Pisces.
These signs are not negative in the "bad" sense, but simply represent the yin to the yang of the positive signs - they tend to be more introverted, withdrawn, and responsive to outside influences.
For more about these signs, see
.IR earth (2)
and
.IR water (2)
and the pages for each of the individual signs.