.TH рыбы 4 . . "вики stars"
.SH РЫБЫ ♓
.B Управляющие:
Юпитер, Нептун
.br
.B Качество:
Мутабельное
.br
.B Стихия:
Вода
.br
.B Полярность:
Негативная
.br
.B Дом:
12-ый
.br
.B Родились:
19 февраля - 20 марта
.br

Рыбы — последний знак зодиака. 
Те, у кого солнце в знаке Рыбы, обычно интроспективные, чуткие, и спокойные, и чувствуют эмоции больше, чем другие. Рыбы также могут быть наивными и чувствительные к манипуляции. 
.br
 
.br
Интересный факт: Думают, что Иисус Христос был Рыбами!