.TH STARS 1
.SH НАЗВАНИЕ
stars \- вызов астрологических функций
.SH ОБЗОР
.B stars
[
.B -dtz
]
.I планета
.br
.br
.B stars -b
[
.B -dglqtvz
]
.I имя-профиля
.br
.br
.B stars -H
[
.B -dz
]
.I имя-профиля
.br
.br
.B stars -i
.I (страница)

.SH ОПИСАНИЕ
.I stars
предоставляет набор астрологических инструментов, направленных на создание гораздо более дешевого эквивалента консультации профессионального астролога.
Доступны четыре различных режима: планетарный режим, режим профиля, режим гороскопа и режим вики (
соответственно с параметрами, перечисленными в
.B ОБЗОРЕ
).
.br
.br
Следующие (с учётом регистра) допустимые значения для
.I планет:
.br
.br
.B su[n], ea[rth]
- (геоцентрическое) Солнце
.br
.br
.B mo[on]
- (геоцентрическая) Луна
.br
.br
.B me[rcury]
- (гелиоцентрический) Меркурий
.br
.br
.B ve[nus]
- (гелиоцентрическая) Венера
.br
.br
.B ma[rs]
- (гелиоцентрический) Марс
.br
.br
.B ju[piter]
- (гелиоцентрический) Юпитер
.br
.br
.B sa[turn]
- (гелиоцентрический) Сатурн
.br
.br
.B ur[anus]
- (гелиоцентрический) Уран
.br
.br
.B ne[ptune]
- (гелиоцентрический) Нептун
.br
.br
.B pl[uto]
- (гелиоцентрический) Плутон
.br
.br
.B er[is]
- (гелиоцентрическая) Эрида
.br
.br
.B ce[res]
- (гелиоцентрическая) Церера
.br
.br
.B ch[iron]
- (гелиоцентрический) Хирон
.br
.br
Требуются только первые двe буквы имены любого небесного тела, остальные будут проигнорированы.
.br
.br
В режиме планеты
.I stars
будет производить все активные транзиты астрального тела, в каком знаке и доме оно находится, а также дополнительные характеристики. Требуется действительная
.I планета
как параметр.
Также может использовать флажки
.B -d, -t
и
.B -z
чтобы посмотреть на тело в определенное время, а не прямо сейчас.
.B -z
может указать часовой пояс где указывается время.
По умолчанию используется часовой пояс компьютера.
Эта опция не нужна только если вы не укажете
.B -d
и / или
.B -t.
.B -d
дата должна быть в формате ММ/ДД/ГГГГ.
Это должна быть дата в указанном часовом поясе.
По умолчанию это
.I tmnow(2).
.B -t
должено быть время в форме ЧЧ:ММ:СС.
Секунды не могут быть пропущены.
.br

.br
В режиме профиля
.I stars
создает профиль пользователя и предоставляет карту рождения пользователя.
Предоставленные данные хранятся в / lib / stars / profile / [имя] и могут быть повторно использованы для воспроизведения карты рождения или составления индивидуальных гороскопов.
Здесь,
.I stars
допускает параметры [
.B -dglqtvz
].
.B -d
.B -t
и
.B -z
требуют того же формата ввода и имеют те же значения по умолчанию, что
и в режиме планеты, но здесь Вы должны указать дату, время и часовой пояс рождения (соответственно) для профиля.
.B -l
indicates the latitude and longitude of birth and should be in the format
.B -l
ШИРОТА,ДОЛГОТА.
Широта и долгота должны быть в десятичном формате, а не в градусах / минутах / секундах. По умолчанию используется экватор и нулевой меридиан.
.B -g
допускает параметр формы [NMF] [NMF], указывающий местоимения, которые будут использоваться программой при обращении к человеку, представленному профилем, и его предполагаемым партнерам. N означает нейтральный («они»). По умолчанию - NN.
